# Generated by Django 2.1.7 on 2019-04-11 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_first', '0004_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('card', 'card'), ('qiwi', 'qiwi'), ('cash', 'cash')], default='card', max_length=10),
        ),
    ]
