# Generated by Django 2.1.7 on 2019-04-11 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_first', '0006_auto_20190411_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('cash', 'cash'), ('qiwi', 'qiwi'), ('card', 'card')], default='card', max_length=10),
        ),
    ]
